### ISSUE TITLE
more currencies

### ISSUE THREAD

**Issue by paulle** [billthefarmer/currency#1]
First thank you for this nice programme. Do you think about adding more currencies in the future? Like Peruvian sol, Cuban peso, Dominican and Argentine currencies etc.

**Comment by billthefarmer** [comment]
The data comes from the [European Central Bank](http://www.ecb.europa.eu/stats/exchange/eurofxref/html/index.en.html) and is limited to the currencies on that page. If you want a more comprehensive app, the [XE Currency](https://play.google.com/store/apps/details?id=com.xe.currency) app on the app store is much more comprehensive. The ECB data is free of change, xe.com want a lot of money for their data.

**Comment by paulle** [comment]
Thank you for the information. I understand now why only a limited set of currencies is possible.

Am 12. Dezember 2016 20:34:17 MEZ schrieb Bill Farmer <notifications@github.com>:
>The data comes from the [European Central
>Bank](http://www.ecb.europa.eu/stats/exchange/eurofxref/html/index.en.html)
>and is limited to the currencies on that page. If you want a more
>comprehensive app, the [XE
>Currency](https://play.google.com/store/apps/details?id=com.xe.currency)
>app on the app store is much more comprehensive. The ECB data is free
>of change, xe.com want a lot of money for their data.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/billthefarmer/currency/issues/1#issuecomment-266528815

-- 
K-9 Mail

**Comment by landry314** [comment]
This app does 180 currencies and is free and open source:
https://github.com/samanyougarg/Currency-Converter-Android/

Maybe you could search the code and find out how they get the data for free.

**Comment by billthefarmer** [comment]
They get it from here: https://currencylayer.com. Interesting they claim 
180 currencies and the site says 168.
