### ISSUE TITLE
Item selection lost on orientation change

### ISSUE THREAD

**Issue by reverse-unina** [billthefarmer/currency#11]
When i perform this sequence of events, the item selection disappears:

Sequence 1:
1. Long click on item in currency list
2. Orientation Change

Sequence 2:
1. Click on Add icon
2. Long click on items in list
3. Orientation Change

**Comment by billthefarmer** [comment]
Ok, didn't save the selection list. That will be in the next version.

**Comment by gugakatsi** [comment]
guess i can fix that

**Comment by billthefarmer** [comment]
Fixed in the previous version.
