### ISSUE TITLE
Unable to use a comma as decimal point

### ISSUE THREAD

**Issue by vsandre** [billthefarmer/currency#13]
I am using Currency 1.07 from F-Droid at Android 7.1.1 with German settings.

I am unable to input a decimal number others than integers. E.g. 1,15 EUR wich is 1,00 GBP is not possible. The problems is that a click on the comma is not recognized. Using a point instead, which will be inserted in the field, is not recognized as a decimal point. For example 1.15 EUR are 100,00 GBP.

**Comment by vsandre** [comment]
BTW The program it self displays the separation correctly with a comma.

**Comment by billthefarmer** [comment]
This appears to be a long standing issue with numeric input in Android, which as far as I can tell is still outstanding: https://code.google.com/p/android/issues/detail?id=82993. There appear to be various workarounds, I will investigate.

**Comment by billthefarmer** [comment]
I have posted a new version with a workaround. It will allow input of both commas and points. If the input is correct for the locale, it will be interpreted correctly. The bug appears to be just in the numeric keypad.

**Comment by vsandre** [comment]
Works, thank you for the fast reaction.
