### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [billthefarmer/currency#14]
Hi @billthefarmer 

I found [this app on the Google Play Store](https://play.google.com/store/apps/details?id=com.converter.currency). This guy just took the source code, added some adds and put it on the Google Play Store

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) if it's your wish ;)

Don't forget to tell Google that:
* The app is licensed under GPL3 and this guy is violating it by distributing the app without the source code;
* He is falsely claiming he made the app;
* Also tell them that this guy has done the same thing already with other apps. Probably this is worth mentioning. (I watch him)

**Comment by Poussinou** [comment]
I hunt them, I alerted 4 developers like you today.
I contribute to FLOSS Android Apps who belongs to F-Droid, like yours ;)
Have fun reporting this man...

**Comment by billthefarmer** [comment]
Well that was a bit nebulous, I got an email from Google asking for a screenshot, when I replied they said they couldn't find it. The play store page says it's not available in your country, so I sent Google a screenshot of their play store app showing it installed on my phone. I can only assume it was taken down by the developer. However it still showed up in the app store on my phone.

**Comment by Poussinou** [comment]
The same for me on Google Chrome, it's not available in France. I assume the fake developer is watching this thread...
Maybe try to use Tor to access the Google Play Store from another country from your computer...

**Comment by billthefarmer** [comment]
Well that was fun, that must be a standard message when something is taken down. I got:

Det här innehållet är tyvärr inte tillgängligt i ditt land ännu.
Vi jobbar på att lansera ditt favoritinnehåll i fler länder så snart som möjligt.
Kom snart tillbaka.

На жаль, цей вміст наразі не доступний у вашій країні.
Ми намагаємося зробити ваш улюблений вміст доступним у більшій кількості країн якомога швидше.
Перевірте доступність вмісту пізніше.

Paumanhin! Hindi pa available ang nilalamang ito sa Google Play sa iyong bansa.
Nagsusumikap kami na dalhin ang nilalamang gustung gusto mo sa higit pang mga bansa nang mabilis hangga't maaari.
Mangyaring bumalik sa lalong madaling panahon.

Tha's Swedish, Ukranian and Filipino, according to Google translate.

**Comment by Poussinou** [comment]
Very crazy xD
Using Tor Browser, it looks like the app is blocked in every country in the world, but it's not taken down...

Anyway, we can now both speak Swedish thanks to Google :smile:

**Comment by Poussinou** [comment]
@billthefarmer The [fake developer](https://play.google.com/store/apps/dev?id=8641344094929372114) does not have any app anymore. I'll close this issue now !

(I'll keep an eye on him, if you find any other new copyright violation, please ping me and give me te link ;) )
