### ISSUE TITLE
Add other exchnage rates

### ISSUE THREAD

**Issue by gabm** [billthefarmer/currency#15]
Thanks for this great app! I found it in f-droid store and got happy, it would be very useful as our holidays are coming up...

Unfortunately the amount of currencies is rather limited. It seems your source doesn't provide more rates, right?

Just googled a bit around and came up with this: https://openexchangerates.org/ ... Maybe that would allow more currencies to be displayed?

**Comment by gabm** [comment]
oh sorry, it seems this API is not for free?! :/ what a pitty

**Comment by billthefarmer** [comment]
They do have a free plan which would be OK for a web site that doesn't get too many hits, but it is limited to 1000 requests a month. As I don't have any idea how many people are using this app, but it seems to be fairly popular, I think that limiting the use would cause problems. The ECB offers the most rates for free with no limitations that I could find.
