### ISSUE TITLE
Upgrade from 1.09 to 1.10 fails with "unknown error"

### ISSUE THREAD

**Issue by tomreyn** [billthefarmer/currency#22]
Uising F-Droid 0.102.3, the "Currency" app fails to upgrade from 1.09 to 1.10 with the following message: "installation failed due to unknown error".

Uninstalling 1.09 and installing 1.10 works around this (at the loss of user data).

Since this could be an F-Droid issue (if just the imprecise error message) I have also reported it at https://gitlab.com/fdroid/fdroiddata/issues/954

**Comment by billthefarmer** [comment]
That's my fault, nothing to do with F-Droid, it's down to Android. I changed the target android version.

**Comment by radasbona** [comment]
I have also a fault. "Error -26=null". I use android 6.
Version 1.11 doesn't work too.

**Comment by billthefarmer** [comment]
Yes, as above, you have to uninstall the old version to install the new. That's why I haven't closed this issue, so people can see the fix. The first rule of posting issues is to check the existing ones, and not post 'Me Too' unless you have something significant to report.
