### ISSUE TITLE
Israeli flag and braslian real

### ISSUE THREAD

**Issue by paulle** [billthefarmer/currency#28]
There seems to be an error, showing Israeli flag and Braslian real.
(I#m using the German version of your nice app)
![screenshot_20180117-232053](https://user-images.githubusercontent.com/4852079/35766821-782f56e4-08df-11e8-9c84-efb9dc782b98.png)

**Comment by billthefarmer** [comment]
Yes, there's an error in the German translation. I assume Israelischer Schekel is correct for Israeli Shekel? That will be in the next version.

**Comment by paulle** [comment]
Yes this will be correct. Thank you

Am 3. Februar 2018 13:30:08 MEZ schrieb Bill Farmer <notifications@github.com>:
>Yes, there's an error in the German translation. I assume Israelischer
>Schekel is correct for Israeli Shekel? That will be in the next
>version.

-- 
K-9 Mail
