### ISSUE TITLE
Missing Icelandic currency (ISK)

### ISSUE THREAD

**Issue by KrimaRula** [billthefarmer/currency#30]
I miss the Icelandic currency (ISK) in the app. The currency is offered by ECB. 
ECB offers the rates for 32 currencies, which it converts into euros. So 33 currencies. The app offers 32 currencies. ISK is missing.

**Comment by billthefarmer** [comment]
I originally left it out because the ECB had stopped updating it some time ago - 9 December 2008 according to the graph. Now it's back. I will put it back in.

**Comment by KrimaRula** [comment]
Thanks
