### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by tortugaverde98** [billthefarmer/currency#33]
Thank you for Currency on F-droid. Please post your btc address on your f-droid page and on your github page.

**Comment by billthefarmer** [comment]
[Kill the blockchain! It'll make you fitter in the long run, honest](http://www.theregister.co.uk/2018/06/01/kill_the_blockchain_itll_make_you_fitter_in_the_long_run/)
[Buffett blasts bitcoin as 'mirage': 'Stay away!'](https://www.cnbc.com/2014/03/14/buffett-blasts-bitcoin-as-mirage-stay-away.html)

**Comment by tortugaverde98** [comment]
Yes, we should certainly trust what the mainstream 'experts' tell us. We should also trust our governments, microsoft, google, and facebook. FOSS is only for tinfoil hat silly people.

Bitcoin is FOSS money.  Bitcoin is the only way many FOSS fans will be able to support your work. Please consider it. Your donations await you.
