### ISSUE TITLE
Feature Request: Two pane view

### ISSUE THREAD

**Issue by nulledone** [billthefarmer/currency#34]
After reading the markdown, I see that you don't want any cosmetic improvement, but this one would be very useful for me.

Idea is basically an option to divide from center and ability choose different currencies in each pane, totally independent to other pane. Like running a clone of the app.

Also thank you for your great contribution to open source community.

**Comment by billthefarmer** [comment]
I've looked at this. It's possible to get two apps running split screen, but you don't appear to be able to get two copies of the same app running concurrently.

![screenshot_20180805-100621](https://user-images.githubusercontent.com/3448386/43707730-a10699a8-9960-11e8-973c-0f49f38f8b79.png)

It would be a major redesign to have a split screen view of this app, and it might not work too well on small devices.

**Comment by nulledone** [comment]
Thanks for the answer,

My opinion is that you can make pane an option as not everybody might want it, or at least a swipe to next pane could be useful.
