### ISSUE TITLE
Request Feautre updates by phone inet

### ISSUE THREAD

**Issue by DemonRem** [billthefarmer/currency#36]
Can i update the gated with my phone internet???

**Comment by billthefarmer** [comment]
![image](https://user-images.githubusercontent.com/3448386/44477169-d0b60c00-a631-11e8-8269-d183cebc396f.png)

Turn the Update on WiFi only option off. It's on by default so as not to use data unnecessarily.

**Comment by DemonRem** [comment]
Huh sorry didnt saw it
