### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by ewuoso** [billthefarmer/currency#43]
About us section a section that allows users learn more a out your project. If you will allow me.  I can create that for you

**Comment by billthefarmer** [comment]
The app has an about item which gives the copyright, licence, version and build date. More info about me can be seen on my [GitHub page](https://github.com/billthefarmer), which has link to my [web page](http://billthefarmer.github.io), and from there to my [blog](https://billthefarmer.github.io/blog).
