### ISSUE TITLE
More currencies possible?

### ISSUE THREAD

**Issue by uspoma** [billthefarmer/currency#44]
Hello.

Thanks for this app - it's clean and simple and does what one expects.
I miss some currencies - especially the African continent is underrepresented.

Would it be possible to add more African countries to the list of currencies?

Best,
uspoma

**Comment by billthefarmer** [comment]
This issue is continually being raised, despite what I wrote in the [README](https://github.com/billthefarmer/currency/blob/master/README.md#extra-currencies). See #17. Always check closed issues.  I can't add currencies that are not available from a free and reliable source.
