### ISSUE TITLE
Feature request: Chart range presets

### ISSUE THREAD

**Issue by baarkerlounger** [billthefarmer/currency#45]
Appreciate the functionality is already present by being able to pinch to zoom in and out of charts but having some presets would be really helpful. For example 5D, 1M, 3M, 6M, 1Y, 5Y, Max.

(Also as a side note the chart function might be a bit more intuitive to find if it appeared in the top bar when you long press a currency along with the ✓ and x rather than being in the overflow? Seems like there's space for it).

**Comment by billthefarmer** [comment]
OK, chart range presets are possible, I will investigate.
The number of items in the toolbar before overflowing on to the menu is determined by the device size. On a tablet you get four items in landscape and portrait, on a phone you get three in portrait and four in landscape. On a small phone it may be less. It can be overridden, but that can cause overlap.

**Comment by billthefarmer** [comment]
OK, that works, it will be in the next version after I have done the translations.
