### ISSUE TITLE
Connection to myracloud

### ISSUE THREAD

**Issue by stef204** [billthefarmer/currency#46]
I see this connecting to myracloud.com
Is this your own instance at that domain?
And the only way you can serve the info?  Can you please explain?
Thanks.

**Comment by billthefarmer** [comment]
I've never heard of myracloud. The app connects to the [ECB](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html), using standard android web APIs [here](https://github.com/billthefarmer/currency/blob/master/src/main/java/org/billthefarmer/currency/Main.java#L161).

**Comment by stef204** [comment]
To look at connections, I used an app (available on F-Droid) called Net Monitor by Secuso.  I believe it uses the VPN method to sniff connections.  It could be that app connecting to myracloud.com perhaps.

Here is the screenshot of what it shows:
![gscreenshot_2018-12-07-184325](https://user-images.githubusercontent.com/8831808/49664141-e9afc500-fa48-11e8-9771-c4ebbca3aa64.png)

As soon as I find a moment, I will use tcpdump instead and post again.

Thanks for your quick answer.

**Comment by billthefarmer** [comment]
Myracloud must be the ECB's ISP.
```shell
$ ping www.ecb.europa.eu
Pinging www-ecb-europa-eu.ax4z.com [185.5.82.138] with 32 bytes of data:
Request timed out.
Request timed out.

Ping statistics for 185.5.82.138:
    Packets: Sent = 2, Received = 0, Lost = 2 (100% loss),
Control-C
$ tracerte 185.5.82.138
Tracing route to xb905528a.host.myracloud.com [185.5.82.138]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  192.168.1.254
  2    21 ms    21 ms    21 ms  84.93.253.112
  3    22 ms    21 ms    21 ms  84.93.253.115
  4    22 ms    22 ms    22 ms  core1-be1.southbank.ukcore.bt.net [195.99.125.130]
  5    22 ms    22 ms    22 ms  peer5-hu0-2-0-2.telehouse.ukcore.bt.net [213.121.193.201]
  6    23 ms    23 ms    22 ms  t2c4-et-3-3-0-0.uk-lon1.eu.bt.net [166.49.211.246]
  7    23 ms    21 ms    22 ms  ae9-0.lon10.core-backbone.com [5.56.18.249]
  8    44 ms    38 ms    37 ms  ae6-2003.nbg20.core-backbone.com [80.255.14.81]
  9     *        *
```

**Comment by stef204** [comment]
Before opening this issue, I looked (very cursorily) at myracloud.com and it seemed like a very small shop; and I couldn't really fathom how the ECB could have any dealings with what looked like a micro enterprise, at first glance.<br>
But you're right, it looks like the ECB has their DDOS protection with them or some other service like CDN, etc.<br>
Thanks for providing feedback.<br>
I will close this issue.
