### ISSUE TITLE
Correct currency symbol position

### ISSUE THREAD

**Issue by IAmNotImportant** [billthefarmer/currency#47]
Currently all currency symbols are being displayed before the numerical value. As this is valid for some currencies (pound, dollar), some have it the other way - czech crowns (Kč), polish zloty (zl) and others.

I think it shouldn't be too hard to add another boolean array to specify symbol position - am I right?

**Comment by billthefarmer** [comment]
I originally cribbed the layout of this app from the excellent [XE Currency](https://play.google.com/store/apps/details?id=com.xe.currency) app. I just checked it out again, and although it has been updated since, they get it wrong as well, if you are correct.

**Comment by IAmNotImportant** [comment]
It seems that XE is Canada-based company, so I wouldn't be surprised they got it wrong, considering that both Canada and US have the symbol before value and they may have not seen other currency representations.

The currencies that have symbol first are
`eur (€), usd ($), jpy (¥), gbp (£), (? ...)`

and those which have number (and space) first:
`bgn (лв), czk (Kč), dkk (kr), huf (Ft), pln (zł), ron (lei), sek (kr), chf (Fr/SFr), nok (kr), hrk (kn), ...`

**Comment by billthefarmer** [comment]
I did some searching on this. Apparently the position of the currency symbol should be where a user using the locale the device is set to would expect it, not where a user of that currency would expect it.
