### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by GitHubHatesTor** [billthefarmer/currency#5]
I found this new app on F-Droid so I tried it(and I was looking for a simple currency check app).

Unfortunately, I couldn't use it because it lacks HTTP/SOCKS support. Especially "Orbot" users.

e.g.,

Settings:
[X] Enable HTTP Proxy
"Set proxy" -> input "1.2.3.4:8888" -> tap "OK"

**Comment by billthefarmer** [comment]
There is not a great deal of point in putting proxy support in an app as Android provides support for setting up a proxy or a VPN for all apps. There is also apps that will do it for you.
