### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by IZ2QDH** [billthefarmer/currency#50]
I'm available to translate the app in italian

**Comment by billthefarmer** [comment]
OK, thank you. There are two files - https://github.com/billthefarmer/currency/blob/master/src/main/res/values/arrays.xml and https://github.com/billthefarmer/currency/blob/master/src/main/res/values/strings.xml. You can either clone the repository, add your translation, and send a pull request, or just post your translation here and I will add it.

Or there is an app - [Stringlate](https://github.com/LonamiWebs/Stringlate), which you can get from F-Droid that does all the technical stuff for you.
