### ISSUE TITLE
Move the replaced currency to the top of the list

### ISSUE THREAD

**Issue by zekooooo** [billthefarmer/currency#53]
Right now when I click a currency from the list to replace the one that's being compared with, the old, replaced currency goes to the bottom of the list. Since I usually compare 3-4 currencies, this means I constantly have to scroll to the bottom, which is normally obscured by the keyboard.

If you instead put the replaced currency on the top of the currency list (and shift the other ones one place down), recently used currencies will stay near the top and least used ones will gravitate to the bottom. This way the more used ones will both be visible without moving screen or turning off keyboard, and they'll visually be together with the selected currency that's being compared against.

**Comment by billthefarmer** [comment]
It used to work like that. I made the change in response to #48. As @AluminiumTech hasn't responded I could change it back in the next release.

**Comment by zekooooo** [comment]
Thanks, that would be great. This way you could also reorder items, you'd just have to select them in reverse order and then reselect the original selected currency.
