### ISSUE TITLE
Using Fixer.io

### ISSUE THREAD

**Issue by SecT0uch** [billthefarmer/currency#54]
Hi, thanks for this awesome application, I'm using it on a daily basis.
Unfortunately, the ECB doesn't provide many currencies.
Have you considered using the [fixer.io](https://fixer.io/) API?
The free version is limited to 1000 API calls a month. (I don't know at all if it would be doable)
They also have a  [github repo](https://github.com/fixerAPI/fixer)

**Comment by billthefarmer** [comment]
See #17, #44

**Comment by SecT0uch** [comment]
My bad, the search function of my app is broken.
