### ISSUE TITLE
Add more international currencies to the app for other countries.

### ISSUE THREAD

**Issue by chrisbarth01** [billthefarmer/currency#56]
#### Repository

https://github.com/billthefarmer/currency

#### Project name

Currency

---

#### Components

I do understand that the developer has added over 30 international currencies in the app but I please want to request that he adds more international currencies. Maybe Some of the West African currencies like Nigerian Naira, Ghanaian Cedis, etc. 

---

#### Proposal Description

This beautiful app isn't created for the use of specific countries; anyone from anywhere can use it at anytime. But then, what of those whose currency isn't listed on the app? Do they uninstall the app which would have solved their problem? I checked out for my country's currency but wasn't happy when I discovered that it isn't available. I know that developing isn't any bit easy but I please suggest that more currencies should be added to the app. Even if it won't be West Africa currencies as I have proposed, I'll be glad to see more international currencies on the list, not just me; other users will be glad too. 

---

#### Mockups / Examples

Below is a mock-up of my suggestion, it is an edited screenshot;
![PicsArt_05-08-11 26 37](https://user-images.githubusercontent.com/49325171/57370337-d768bd00-7187-11e9-972f-bccc750bd10b.png)

---

#### Benefits

- If the developer adds more currencies, they'll be more users from different countries and besides, the app would be more interesting to use. 

---

#### Conclusion

This suggestion is quite important since this app isn't restricted from any country. I hope that the developer can hear me and consider increasing the number of currencies on the app.

**Comment by billthefarmer** [comment]
Before making this sort of request, read the README, and the closed comments. You have provided no free and reliable source of data.
