### ISSUE TITLE
Add an inbuilt calculator in the Currency app

### ISSUE THREAD

**Issue by chrisbarth01** [billthefarmer/currency#57]
#### Components

In this contribution, I am requesting that an inbuilt calculator feature should be added.

---

#### Proposal Description

I am requesting that a calculator feature should be added to the Currency app. Most users like me don't just want a currency conversion app to only convert currencies; sometimes I have to do some calculations using the result from two currency conversion or more. This feature will help users to complete all their calculations using the same currency conversion application. It doesn't really look nice when I copy a currency conversion and I paste it on a different application to perform some multiplication, division, addition, subtraction, etc calculations. 

---

#### Mockups / Examples

Below is a mock-up of my suggestion, it is a screenshot from an app;
![20190508-111529](https://user-images.githubusercontent.com/49325171/57371748-835fd780-718b-11e9-9e86-9708e34ddbc7.png)

---

#### Benefits

- If the developer adds this feature, users won't bother to use external calculators to complete their calculations; users can perform all their calculations in the app. 

---

#### Conclusion

This suggestion is another important feature since we are talking of currencies (money). Everything about money is calculation therefore it is necessary for a currency conversion application to have an inbuilt calculator which will help users to complete their calculations in the app.

**Comment by billthefarmer** [comment]
AFAIK, every device includes a calculator app. I have no intention of duplicating existing apps.

**Comment by chrisbarth01** [comment]
I am not asking you to duplicate a calculator, but to add a calculator for currencies....... It isn't the normal calculation that would be performed, but calculations relating to exchanges/conversions
