### ISSUE TITLE
manually add currency

### ISSUE THREAD

**Issue by ilf** [billthefarmer/currency#61]
I love this app. And I understand the problems of [Extra currencies](https://github.com/billthefarmer/currency#extra-currencies) - mostly bad data sources.

However, travelling with exclusively this app again, I had an idea. How about letting users manually add a currency that's not available from your data sources? That would enable users to calculate conversions (the easy to implement part) but *not* to update rates (the hard part). Sure, this would be inexact after a few days, but good enough for most people travelling for short periods. And users could still manually open XE (or whatever) in a browser and input the current rate snapshot.

I for one would find this incredibly useful. What do you think?

Thanks, and keep up the good work!

**Comment by billthefarmer** [comment]
OK, I have produced a new version with an extra currency, with a dialog to update the rate against the Euro.

**Comment by ilf** [comment]
@billthefarmer Thanks, this is cool! Using 1.30 from F-Droid, I am able to add the extra currency, but I don't see a dialog to set the rate.

Steps to reproduce:

1. "+"
2. "EXT" at very bottom
3. "EXT" is added 1:1 to EUR.

Long pressing "EXT" gives: "✓", "X" and a dropdown menu with "Chart" and "Copy. Neither can set the rate.

What am I doing wrong?

Thanks!!

**Comment by billthefarmer** [comment]
Because you can only set the rate for the extra currency, it's on the main menu. Update pops up a dialog to enter the rate. That is in the help.

**Comment by ilf** [comment]
@billthefarmer Thank you, that works!

I'm not sure how intutitive it is from a user POV.

1. IMHO, the settings in the burger menu affect *all* currencies, but this one just affects this one.
2. The option is called "update" - that's highly ambiguous - what does it update? How about renaming it to "set extra"?

Best!

**Comment by billthefarmer** [comment]
If I put it on the select menu users will expect it to update the selected currency rate, which it doesn't. The dialog is clearly labelled 'Update extra currency'. The icon which appears in landscape is the closest I can find to the appearance of a dialog box. The only item on the main menu which affects all currencies is refresh, which again has a suitable icon.

**Comment by guushoekman** [comment]
Very useful feature, thank you for implementing it!

Just wanted to say that I had to look up this issue to find out how to edit the extra currency. I personally find it very unintuitive. The word update is quite ambiguous and I agree with @ilf that 'set extra' would make things a lot more clear.

It would also be great if the extra currency could ve remained. I'm on a trip through multiple countries with unsupported currencies. It would be nice if I could label them to avoid confusion.

**Comment by billthefarmer** [comment]
The update function for the extra currency is clearly explained in the [README](https://github.com/billthefarmer/currency#toolbar) here and in the help built in to the app.

![Screenshot_20191227-082043 1](https://user-images.githubusercontent.com/3448386/71509244-9cd0a380-2882-11ea-98a9-d5a02112c049.png)
