### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [billthefarmer/currency#68]
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688
That was simply information about what is still possible. You would then only have to enter the
screenshots in fastlane. This is just one way that you can also add screenshots to the app view
if you can. If you added screenshots (then F-Droid is happy) and if you can't add any -> then
you can close the issue because it was only an info. Thank you that your app is available in
fdroid. Very much for your attention.

**Comment by billthefarmer** [comment]
I'm a bit puzzled by this because I have screenshots in F-Droid...

![Screenshot_20210219-084040 1](https://user-images.githubusercontent.com/3448386/108480119-73e14e00-728e-11eb-9e3b-04a64d0597f7.png)

**Comment by mondlicht-und-sterne** [comment]
Okay thats awesome. Than can i close this issue
