### ISSUE TITLE
Select all text when clicking the value field

### ISSUE THREAD

**Issue by Nutomic** [billthefarmer/currency#7]
If there's already a value set, and I want to change it, its rather complicated to change. First I have to select the EditText, then backspace to delete the current value, and enter the new value.

Instead, clicking the EditTedt should select all text, so you can start typing immediately.

**Comment by billthefarmer** [comment]
If instead of just touching the field you do a long touch the whole text is selected and the system cut/copy/paste menu appears. You can then do any of those or just start typing. I will look at that.

**Comment by billthefarmer** [comment]
Well I tried that and it didn't work. If you do EditText.selectAll(), it just moves the cursor to the start of the text, irrespective of where you clicked. It's probably not a good idea to try and change the standard Android user interface behavior.

**Comment by Nutomic** [comment]
Firefox does this for the address bar, and it works really well there. Long click also works, but is a bit harder to figure out.

**Comment by billthefarmer** [comment]
Ok, I'd already tried two different ways of doing this that didn't work. 
I've now tried two more and found one that works. It can be a bit 
disconcerting, so I've put an option in the settings to turn it off. 
That will be in the next version.
