### ISSUE TITLE
blanc currency

### ISSUE THREAD

**Issue by paulle** [billthefarmer/currency#70]
Thank you for currency.
Sometimes it would be useful to have a blanc currency field.
There you can put a value for
currencies which aren't in your list. The value can be served in the net and then putted in the blank field.

**Comment by billthefarmer** [comment]
There is an extra currency at the end of the list, and a menu entry to update it.

![Screenshot_20210513-091714 1](https://user-images.githubusercontent.com/3448386/118098703-1f9cc480-b3cc-11eb-9b24-e0c0ce6c2e6f.png)

**Comment by paulle** [comment]
Thank you, excuse me for being stupid.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
