### ISSUE TITLE
Traffic

### ISSUE THREAD

**Issue by bastireg** [billthefarmer/currency#73]
Genrates over 2.6 GB Traffic in a few days...

Android 11 with Version 1.38 from F-Droid Store.

**Comment by billthefarmer** [comment]
You must do some extreme updating. I just downloaded the three files the app uses.
```
-rw-r--r-- 1 Bill 197121 1.7K Aug 10 10:16 eurofxref-daily.xml
-rw-r--r-- 1 Bill 197121 6.4M Aug 10 10:15 eurofxref-hist.xml
-rw-r--r-- 1 Bill 197121  75K Aug 10 10:14 eurofxref-hist-90d.xml
```
The large file is only downloaded if you touch the **Historical** item in the **Chart** part of the app. There is a warning about this in the README and in the app help file. To put the app data usage in context, here are a couple of screenshots of data usage on my tablet, which is WiFi only.

![Screenshot_20210810-100849_Settings 1](https://user-images.githubusercontent.com/3448386/128842970-d973c628-536b-4536-80fc-7626d8eccaee.jpg)

![Screenshot_20210810-101006_Settings 1](https://user-images.githubusercontent.com/3448386/128843029-e44e6b02-1baa-4e9c-9bf4-155ca53e8c5c.jpg)
