### ISSUE TITLE
App crash when Russian ruble is in the list (v1.41)

### ISSUE THREAD

**Issue by juneyourtech** [billthefarmer/currency#74]
If the Russian ruble is one of the listed currencies in the app, the app will crash on start when the phone is online, regardless of OS version (I have Android 4.1.2 and 9.0).

Reinstalling helped, but attempting to add the Russian ruble will also crash the app. Starting the app after that solves the issue, but the Russian ruble won't have been added.

**Comment by juneyourtech** [comment]
I'm seeing similar issues at the ECB's own currency converter, with no data visible for 2 March 2022, but data visible for 1 March 2022.

Link here:

https://sdw.ecb.europa.eu/curConverter.do?sourceAmount=1.0&sourceCurrency=USD&targetCurrency=RUB&inputDate=01-03-2022&submitConvert.x=81&submitConvert.y=14

**Comment by billthefarmer** [comment]
Yes, they have stopped reporting it in the data. I have fixed the app so it doesn't crash when that happens.

**Comment by juneyourtech** [comment]
I forgot to add, that APK installation would also fail, unless I turn off networking (Wi-Fi or mobile), probably if the ruble is also set.
