### ISSUE TITLE
Unable to select Russian Rouble

### ISSUE THREAD

**Issue by Apollucas** [billthefarmer/currency#76]
The app overall works fine, however I'm unable to select the Russian Rouble even though it appears on the list. Given the 'current situation', is this intentional?

**Comment by billthefarmer** [comment]
The ECB have dropped it from their data.On 18 Mar 2022 10:13, Apollucas ***@***.***> wrote:
The app overall works fine, however I'm unable to select the Russian Rouble even though it appears on the list. Given the 'current situation', is this intentional?
