### ISSUE TITLE
[Feature]  Add settings option for enabling additional % foreign tx fee

### ISSUE THREAD

**Issue by re42** [billthefarmer/currency#79]
Can you add something like this in the settings, so that the user is able to calculate a more realistic exchange rate from their banks?
This screenshot is taken from another currency app
![2022-03-30_1](https://user-images.githubusercontent.com/57980549/160846701-1b897509-6656-4475-bd50-26d69869e80e.jpg)

it is depicted by the 2 red arrows

But in this case, instead of hardcoding 2.2%, let the user decide what percentage they want to add onto the current exchange rate

**Comment by re42** [comment]
> The rates shown by the app are market rates published by the ECB, which is not the same as offered by banks or transfer companies

This is exactly the reason a user would want to enable this option and put an extra % **added onto the rates** from the ECB, so they can get a more realistic number when viewing how much the rate is, so i have no idea why you say its meaningless?

**Comment by billthefarmer** [comment]
It is not the function of app developers to explain the foreign currency market. Rates offered are either sell or buy rates, again which is not what the app gets from the ECB, which is AFAIK the mid market rate. They also add a fee as a percentage. Therefore just adding a percentage is meaningless. The app you showed above probably shows the rates offered by whoever published the app, so adding their percentage would make sense.
