### ISSUE TITLE
Widget is too big and when decreased in width, the country flag doesnt decrease

### ISSUE THREAD

**Issue by re42** [billthefarmer/currency#80]
As the title says,
if you can make the widget more easily readable by being able to adjust the size of it to a smaller block.

Currently when adjusting it from the width, the country flag size stays the same and the writing goes to the next line.

It would be great if it were more easily adjustable towards the smaller size.

**Comment by billthefarmer** [comment]
How is it 'too big' and on what device? The height of the flag is about the same as the text. I could make the flag slightly smaller, but there is no way to make the flag scale as you adjust the size of the widget.

**Comment by re42** [comment]
Then make the flag smaller?
On any device. Just out of curiosity for you to see what im saying, download the xe.com app and put their widget(which is scaled correctly) on a blank screen and then put your app's widget underneath it so you can see the difference in size and the massive difference in the size of flags.
