### ISSUE TITLE
add numbers/values to historical charts

### ISSUE THREAD

**Issue by aisbergde** [billthefarmer/currency#81]
The historical graphs are important for me, but they are not helpful enough, if they don't contain some numeric values. That's why I currently use other apps which contain not only the chart, but also values and more grid lines inside the charts.
If it is possible to add the information about the data provider and the line for the current exchange rate, it should also be possible to add a grid?
I prefer open source software. The other apps are commercial apps.
Here is a good example what I mean, is has a grid, a way to slide through the dates and to see the rate for a specific day and I can change the time period

![Screenshot_2022-07-02-19-36-49-675_com.digitalchemy.currencyconverter.jpg](https://user-images.githubusercontent.com/9020187/177010722-2a773469-6015-40f3-8e82-b5873037a15a.jpg)

**Comment by aisbergde** [comment]
I just have seen, that it is also possible to slide through the history. I didn't know about this feature, there was no hint about.
So the only missing thing is a grid and options to show a x and y scale.

**Comment by billthefarmer** [comment]
The currency chart has an X axis with dates and two Y axes with values. If you touch the char two cross hairs appear so values can be read from the axes. If you want to find the exact date you can change the range to one week and scroll sideways to show the vertical cross hair. Values can be read off the Y axes to four figures and five with a bit of interpolation. These figures come from the ECB, other data sources will give different values. Also the value will be either a snapshot, or the market closing value or an average of the day's trading, I don't know.

![Screenshot_20220702-190847 1](https://user-images.githubusercontent.com/3448386/177014808-05c5620f-e912-42a1-aab8-9d284236eb9b.png)

**Comment by aisbergde** [comment]
I would like to see what you are showing in the screenshot. But I don't see this. What is wrong in my version?
My version is 1.16.1 from f-droid
and it looks like this:
![Screenshot_2022-07-03-19-17-18-662_de.salomax.currencies.jpg](https://user-images.githubusercontent.com/9020187/177050383-cc4ab695-59eb-4dda-afef-7138ced34ca0.jpg)

a deeper precision would be fine. precision 3 is not enough in this example.

**Comment by aisbergde** [comment]
Oh, it looks like I am opening an issue in a wrong repository for a different app.
Now I installed your app "Currency", the. other app I wrote about is "currencies"
Now I installed your app. But come currencies can be added, some can't be added. For example I am not able to add RUB, most other apps can be added. But RUB is important for me.

**Comment by billthefarmer** [comment]
The ECB have dropped the rouble, so it doesn't appear in the app. My [Specie](https://github.com/billthefarmer/specie) app gets the data from a different source which includes the rouble, but doesn't include historical data.

**Comment by aisbergde** [comment]
I got it, why RUB can't be added.

But could you explain how to get the chart for other currencies, which are supported?

**Comment by aisbergde** [comment]
I found it:
first I need to select
then I need to touch the 3 dot entry
then I can. select a chart

This was not intuitive for me.
Maybe, when a currency will be selected, you could add one more icon left to the 3 dot menu so it will be intuitive clear, that a chart can be opened?
