### ISSUE TITLE
Russian rouble does not display

### ISSUE THREAD

**Issue by christopherlam888** [billthefarmer/currency#82]
Describe the bug

Attempting to add the Russian rouble to the home page of the app displaying currencies has no effect - the Russian rouble does not show.

To reproduce

Steps to reproduce the behaviour:

- Open the app
- Press the + button to add a new currency
- Select the Russian rouble
- The selection has no effect

Expected behaviour

The expectation is that the Russian rouble should appear on the home page among the other currencies in a tile displaying the flag, abbreviation, values, and name.

Suggestion: 

Remove the Russian rouble option from the available currencies.

Smartphone:

Device: Pixel 6
OS: Graphene OS (Android 12)
App Version 1.45

**Comment by billthefarmer** [comment]
See #76, #74. If and when the ECB restore the rouble it will appear again.
