### ISSUE TITLE
Double tap to set vaule to 1

### ISSUE THREAD

**Issue by Mr-Bajs** [billthefarmer/currency#84]
Nice app, though it would be much welcome if you could double tap the flag of your select nation to set the value to 1,00. I mostly use the app just check the exchange rate for 1 amount of currency.
Would make ut much more convinient rather then having to select the form, delete and enter 1.

**Comment by billthefarmer** [comment]
A better solution could be to leave the value of the selected currency as it is and adjust the others to suit.
