### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Wjxfi** [billthefarmer/currency#85]

**Comment by billthefarmer** [comment]
See #82, https://github.com/billthefarmer/currency/issues/76, https://github.com/billthefarmer/currency/issues/74. If and when the ECB restore the rouble it will appear again.

**Comment by billthefarmer** [comment]
If you want the rouble, use my [Specie](https://github.com/billthefarmer/specie) app, as mentioned in the [README](https://github.com/billthefarmer/currency#extra-currencies).
