### ISSUE TITLE
Exchange rate not automatically updating

### ISSUE THREAD

**Issue by undeference** [billthefarmer/currency#86]
The exchange rates don't seem to automatically update, meaning I need to open the app and manually press 🗘. This makes the widget a bit less than ideal for me.

I am using version 1.49 (built 12 Jun 2023 16:43:50) on Android 12.

**Comment by billthefarmer** [comment]
The currency rates are updated by the ECB once a weekday. There is no need to press 🗘, the app updates itself and widgets when started. I investigated automatically updating the widgets when I implemented them, but could not get it to work. I have found a better method which works, that will be in the next version.
