### ISSUE TITLE
Can't add Croatian Kuna (HRK)

### ISSUE THREAD

**Issue by rophgoh** [billthefarmer/currency#88]
Can't add Croatian Kuna (HRK) two the screen, regardless his I try to do so. 
The other currencies seem to work just fine.

**Comment by billthefarmer** [comment]
The ECB dropped the Kuna from their data at the end of last year. You can verify this &ndash; Create a chart by selecting a currency and tapping the **Chart** icon. Tap the **New chart** icon and select the Kuna. You will get a blank chart. Tap on the **Historical** menu item, you will get a chart up till the end of December 2022. You can zoom in using the **Range** menu item.

Try my [Specie](https://github.com/billthefarmer/specie) app for many more currencies including the Kuna.
