### ISSUE TITLE
permission_ add AuthorWebSite and WebSite on fdroid app?

### ISSUE THREAD

**Issue by ghost** [billthefarmer/currency#89]
@billthefarmer 
* is it **ok to add** your & app WebSite link in repo_ app WebSite_ https://billthefarmer.github.io/currency AND AuthorWebSite_ https://billthefarmer.github.io given in repo
* WebSite & AuthorWebSite link in [app fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.billthefarmer.currency.yml) will create a link on fdroid client
* please let me know whether we can update similarly for all of your apps listed on fdroid repo

**Comment by billthefarmer** [comment]
Yes that's fine. Not all my apps have a specific web site, for example Tuner site is https://billthefarmer.github.io/ctuner/.
