### ISSUE TITLE
Feature request: Make number keys show when selecting currency

### ISSUE THREAD

**Issue by vanhoopstallion** [billthefarmer/currency#90]
Hello, 

Super great app. Please can I suggest a feature:

When selecting a currency it would be great if the number keys were shown at the same time. The currency numbers are highlighted for editing, but I need to tap the entry field to get the keyboard to show. Hopefully the video below explains it better

Thank you

https://github.com/billthefarmer/currency/assets/15658313/bde838a1-1720-4c25-a62b-6d7c2cf0791a

**Comment by billthefarmer** [comment]
I design all my apps that have text input to not pop up a keyboard unless requested by tapping on an input field. I find the keyboard popping up annoying, especially as the keyboard usually obscures part of the display. The use cases envisaged for this app are to keep an eye on a range of currencies relative to a particular currency. Once you have set the default currency up to a particular value, you can change it and keep that value without any need for the keyboard. Alternatively if you want to use the app as a calculator for a particular value, tapping on the input field will pop up the keyboard allowing the value to be changed.
