### ISSUE TITLE
Voluntary Translation

### ISSUE THREAD

**Issue by SirCrownguard** [billthefarmer/currency#91]
Hello. I would like to make a voluntary Turkish translation for your application. Is there a language file that you can give me because I don't know about programming? In this way, I can share with you the translation I made in the language file.

**Comment by billthefarmer** [comment]
Thank you. These are the files with all the translatable strings in it: https://github.com/billthefarmer/currency/blob/master/src/main/res/values/strings.xml, https://github.com/billthefarmer/currency/blob/master/src/main/res/values/arrays.xml. You just need to translate the text in the middle, in this case 'Currency':
```xml
  <string name="app_name">Currency</string>
```
You also don't need to translate all of the translation credits, just add your own after the copyright, like this:
```xml
  <string name="copyright">
    Copyright \u00A9 2018 Bill Farmer\n\nDiagramm von <a
    href="https://github.com/PhilJay/MPAndroidChart">MPAndroidChart</a>,
    Deutsche Übersetzung von <a
    href="https://github.com/l1am0">L1am0</a>
  </string>
```

**Comment by SirCrownguard** [comment]
I started translating and came to the currencies. I saw that the currencies are alphabetized according to the codes. But when I translate the country names into Turkish, the alphabetical order changes, like "US" becomes "ABD" in Turkish. Is there any problem in arranging these codes in Turkish alphabetical order?
![image](https://github.com/billthefarmer/currency/assets/143234242/e1763ab3-0666-4a0d-b8e5-7dffa6ea84b1)

Also, how would you like me to share the files with you after I finish translating them? I don't have much experience with GitHub.

**Comment by billthefarmer** [comment]
It doesn't matter what order the strings are in. The currency order is determined by the currency code which doesn't change. You can upload the files to here.

**Comment by SirCrownguard** [comment]
I can't upload an XML file here. Should I upload it as TXT?
![image](https://github.com/billthefarmer/currency/assets/143234242/d9672315-d726-498a-bdb3-05b4c9010480)

**Comment by billthefarmer** [comment]
Yes, just rename it.

**Comment by SirCrownguard** [comment]
Sorry for waiting.
[strings.txt](https://github.com/billthefarmer/currency/files/12458462/strings.txt)
[arrays.txt](https://github.com/billthefarmer/currency/files/12458461/arrays.txt)

**Comment by billthefarmer** [comment]
Thank you that will be in the next version
