### ISSUE TITLE
Inaccurate exchange rates?

### ISSUE THREAD

**Issue by concenit** [billthefarmer/currency#93]
The app is handy because it works offline. It is also handsomely designed. But I find disturbing discrepancies in the most important feature: accurate exchange rates. 

For example, as of today (2023-10-10), the app coverts 25,000 DKK to 3531 USD. This is about 0.5% lower than the rate calculated by other sources, like xe.com (3,550 USD) and wise.com (3,550 USD). And as the amounts grow bigger, the discrepancy is more troubling. 

Could you please look into it?

**Comment by billthefarmer** [comment]
The exchange rates come from the [European Central Bank](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html). Other apps get their rates from other sources.
